/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.controltec;

import com.github.britooo.looca.api.core.Looca;
import com.mycompany.controltec.entidades.Componentes;
import com.mycompany.controltec.entidades.Maquina;
import com.mycompany.controltec.entidades.UsoDeMaquina;
import com.mycompany.controltec.entidades.Usuario;
import com.mycompany.controltec.jdbc.Conexao;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 *
 * @author Lenovo
 */
public class TelaDeCadastro extends javax.swing.JFrame {

    Conexao conexao = new Conexao();
    JdbcTemplate con = new JdbcTemplate(conexao.getDataSource());
    Looca looca = new Looca();
    Long idMaquina = 0L;

    /**
     * Creates new form TelaDeLogin
     */
    public TelaDeCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagensFundo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTurma = new javax.swing.JFormattedTextField();
        cadastrarMaquina = new javax.swing.JButton();
        cadastrarComponentes = new javax.swing.JButton();
        nameRA = new javax.swing.JLabel();
        labelEmpresa = new javax.swing.JLabel();
        lblNomeComponente = new javax.swing.JPasswordField();
        lblModeloComponente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tipoComponente = new javax.swing.JComboBox<>();
        nameSENHA3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela De Login");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        lblTurma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTurmaActionPerformed(evt);
            }
        });
        getContentPane().add(lblTurma);
        lblTurma.setBounds(190, 60, 120, 20);

        cadastrarMaquina.setBackground(new java.awt.Color(255, 255, 255));
        cadastrarMaquina.setForeground(new java.awt.Color(0, 0, 0));
        cadastrarMaquina.setText("Cadastrar Máquina");
        cadastrarMaquina.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cadastrarMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarMaquinaActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarMaquina);
        cadastrarMaquina.setBounds(200, 90, 100, 21);

        cadastrarComponentes.setBackground(new java.awt.Color(255, 255, 255));
        cadastrarComponentes.setForeground(new java.awt.Color(0, 0, 0));
        cadastrarComponentes.setText("Cadastrar Componentes");
        cadastrarComponentes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cadastrarComponentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarComponentesActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarComponentes);
        cadastrarComponentes.setBounds(190, 210, 130, 21);

        nameRA.setBackground(new java.awt.Color(255, 255, 255));
        nameRA.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nameRA.setForeground(new java.awt.Color(255, 255, 255));
        nameRA.setText("Turma:");
        getContentPane().add(nameRA);
        nameRA.setBounds(230, 40, 60, 16);

        labelEmpresa.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        labelEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        labelEmpresa.setText("Control Tec");
        getContentPane().add(labelEmpresa);
        labelEmpresa.setBounds(200, 0, 110, 50);

        lblNomeComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblNomeComponenteActionPerformed(evt);
            }
        });
        getContentPane().add(lblNomeComponente);
        lblNomeComponente.setBounds(90, 150, 120, 19);
        getContentPane().add(lblModeloComponente);
        lblModeloComponente.setBounds(310, 150, 120, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modelo do Componente");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 130, 140, 16);

        tipoComponente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Memória", "Disco" }));
        tipoComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoComponenteActionPerformed(evt);
            }
        });
        getContentPane().add(tipoComponente);
        tipoComponente.setBounds(220, 180, 68, 24);

        nameSENHA3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nameSENHA3.setForeground(new java.awt.Color(255, 255, 255));
        nameSENHA3.setText("Nome do Componente");
        getContentPane().add(nameSENHA3);
        nameSENHA3.setBounds(90, 130, 130, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tecnologia2.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -20, 540, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarMaquinaActionPerformed
        Maquina maquina = new Maquina();
        String identificador = looca.getProcessador().getId();
        Long fkTurma = Long.valueOf(lblTurma.getText());

        List<Maquina> listaDeMaquinas = con.query("select * from dbo.Maquina ",
                new BeanPropertyRowMapper(Maquina.class));

        for (Maquina maquinas : listaDeMaquinas) {
            if (maquinas.getIdentificador().equalsIgnoreCase(identificador)) {
                idMaquina = maquinas.getIdMaquina();
            }
        }

        if (idMaquina > 0) {
            JOptionPane.showMessageDialog(null, "Máquina já cadastrada");
        } else {
            maquina.informacoesMaquina(fkTurma);
            JOptionPane.showMessageDialog(null, "Máquina cadastrada com sucesso");
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_cadastrarMaquinaActionPerformed

    private void cadastrarComponentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarComponentesActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:

        if (lblNomeComponente.getText().isEmpty() != true && lblModeloComponente.getText().isEmpty() != true) {
            String identificador = looca.getProcessador().getId();
            List<Maquina> listaDeMaquinas = con.query("select * from dbo.Maquina ",
                    new BeanPropertyRowMapper(Maquina.class));

            for (Maquina maquinas : listaDeMaquinas) {
                if (maquinas.getIdentificador().equalsIgnoreCase(identificador)) {
                    idMaquina = maquinas.getIdMaquina();
                }
            }

            if (tipoComponente.getSelectedItem().equals("Memória")) {
                System.out.println(idMaquina);
                System.out.println(looca.getMemoria().getTotal());
                Componentes componentes = new Componentes();
                componentes.cadastrarComponente(lblNomeComponente.getText(),
                        lblModeloComponente.getText(), "Memória", idMaquina);
            }
            if (tipoComponente.getSelectedItem().equals("Disco")) {
                Componentes componentes = new Componentes();
                componentes.cadastrarComponente(lblNomeComponente.getText(),
                        lblModeloComponente.getText(), "Disco", idMaquina);

            }
            JOptionPane.showMessageDialog(null, "Componente cadastrado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Algum campo do cadastro está em branco");
        }
    }//GEN-LAST:event_cadastrarComponentesActionPerformed

    private void lblTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTurmaActionPerformed

    private void lblNomeComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNomeComponenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNomeComponenteActionPerformed

    private void tipoComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoComponenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoComponenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarComponentes;
    private javax.swing.JButton cadastrarMaquina;
    private javax.swing.JLabel imagensFundo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelEmpresa;
    private javax.swing.JTextField lblModeloComponente;
    private javax.swing.JPasswordField lblNomeComponente;
    private javax.swing.JFormattedTextField lblTurma;
    private javax.swing.JLabel nameRA;
    private javax.swing.JLabel nameSENHA3;
    private javax.swing.JComboBox<String> tipoComponente;
    // End of variables declaration//GEN-END:variables
}
